#----------------------------------------------------------------------------
#       Make Workspace
#
# $Id: MakeWorkspaceCreator.pm,v 1.19 2006/03/10 18:59:57 elliott_c Exp $
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /usr/local/bin/MPC/mwc.pl 
#----------------------------------------------------------------------------


all: demo_regex regex_tests

clean depend generated realclean $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.demo_regex $(@)
	@$(MAKE) -f Makefile.regex_tests $(@)

.PHONY: demo_regex
demo_regex:
	@$(MAKE) -f Makefile.demo_regex generated all

.PHONY: regex_tests
regex_tests:
	@$(MAKE) -f Makefile.regex_tests generated all

project_name_list:
	@echo demo_regex
	@echo regex_tests
