#----------------------------------------------------------------------------
#       Macros
#----------------------------------------------------------------------------
CXX           = g++
LD            = $(CXX) $(CCFLAGS) $(CPPFLAGS)
AR            = ar
PICFLAGS      = -fPIC
CPPFLAGS      = $(PICFLAGS) $(GENFLAGS) -D_REENTRANT -I"." -I"../CustomRand"
OBJEXT        = .o
OUTPUT_OPTION = -o "$@"
COMPILE.cc    = $(CXX) $(CCFLAGS) $(CPPFLAGS) -c
LDFLAGS       = -L"."
CCC           = $(CXX)
MAKEFILE      = Makefile.test2_circular_queue_in_mmap
DEPENDENCIES  = .depend.$(MAKEFILE)
BTARGETDIR    = ../bin/
BIN           = $(BTARGETDIR)test2_circular_queue_in_mmap$(EXESUFFIX)$(EXEEXT)
CAT           = cat
MV            = mv -f
RM            = rm -rf
CP            = cp -p
NUL           = /dev/null
MKDIR         = mkdir -p
EXEEXT        = 
LIBPREFIX     = lib
LIBSUFFIX     = 
GENFLAGS      = -Wall -std=c++11 -ggdb -O4
LDLIBS        = -l"boost_system$(LIBSUFFIX)" -l"boost_filesystem$(LIBSUFFIX)" -ldl -lpthread $(subst lib,-l,$(sort $(basename $(notdir $(wildcard /usr/lib/librt.so /lib/librt.so)))))
OBJS          = test2_circular_queue_in_mmap$(OBJEXT)
SRC           = test2_circular_queue_in_mmap.cpp
LINK.cc       = $(LD) $(LDFLAGS)
EXPORTFLAGS   = 

#----------------------------------------------------------------------------
#       Local targets
#----------------------------------------------------------------------------

all: $(BIN)

$(BTARGETDIR):
	@$(MKDIR) "$@"

$(BIN): $(BTARGETDIR) $(OBJS)
	$(LINK.cc) $(OBJS) $(LDLIBS) $(OUTPUT_OPTION)

generated: $(GENERATED_DIRTY)
	@-:

test2_circular_queue_in_mmap$(OBJEXT): test2_circular_queue_in_mmap.cpp
	$(COMPILE.cc) $(EXPORTFLAGS) $(OUTPUT_OPTION) test2_circular_queue_in_mmap.cpp

clean:
	-$(RM) $(OBJS)

realclean: clean
	-$(RM) $(BIN)

#----------------------------------------------------------------------------
#       Dependencies
#----------------------------------------------------------------------------

$(DEPENDENCIES):
	@touch $(DEPENDENCIES)

depend:
	-makedepend -Y $(CFLAGS) $(CCFLAGS) $(CPPFLAGS) -f $(DEPENDENCIES) $(SRC) 2> $(NUL)

include $(DEPENDENCIES)
